/* AdministratorMenu
*
* 1.0v 
*
* 26/04/19
*
* Copyright
*/
package windows.menu;

import main.Main;
import windows.added.*;
import windows.modified.*;
import windows.removed.*;

/**
 * 
 * @version 1.0 
 * @author Andrey Marín Chacón
 */
public class AdministratorMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorMenu
     */
    public AdministratorMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modifyBillLabel = new javax.swing.JLabel();
        eliminateClieLabel = new javax.swing.JLabel();
        cashierLabel = new javax.swing.JLabel();
        clientLabel = new javax.swing.JLabel();
        createCashLabel = new javax.swing.JLabel();
        modifyCashLabel = new javax.swing.JLabel();
        administratorMenuLabel = new javax.swing.JLabel();
        eliminateCashLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        createClieLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        modifyClieLabel = new javax.swing.JLabel();
        productLabel = new javax.swing.JLabel();
        billLabel = new javax.swing.JLabel();
        createDepartLabel = new javax.swing.JLabel();
        modifyDepartLabel = new javax.swing.JLabel();
        eliminateDepartLabel = new javax.swing.JLabel();
        createCatgLabel = new javax.swing.JLabel();
        modifyCatgLabel = new javax.swing.JLabel();
        EliminateProdLabel = new javax.swing.JLabel();
        eliminateCatgLabel = new javax.swing.JLabel();
        createProdLabel = new javax.swing.JLabel();
        modifyProdLabel = new javax.swing.JLabel();
        invalidateBillLabel = new javax.swing.JLabel();
        createBillLabel = new javax.swing.JLabel();
        goBackButton = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        queriesMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Menu");

        modifyBillLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        modifyBillLabel.setForeground(new java.awt.Color(0, 0, 255));
        modifyBillLabel.setText("»Modify");
        modifyBillLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyBillLabelMousePressed(evt);
            }
        });

        eliminateClieLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        eliminateClieLabel.setForeground(new java.awt.Color(0, 0, 255));
        eliminateClieLabel.setText("»Eliminate");
        eliminateClieLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminateClieLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminateClieLabelMousePressed(evt);
            }
        });

        cashierLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        cashierLabel.setText("Cashier");

        clientLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        clientLabel.setText("Client");

        createCashLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        createCashLabel.setForeground(new java.awt.Color(0, 0, 255));
        createCashLabel.setText("»Create");
        createCashLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createCashLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createCashLabelMousePressed(evt);
            }
        });

        modifyCashLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        modifyCashLabel.setForeground(new java.awt.Color(0, 0, 255));
        modifyCashLabel.setText("»Modify");
        modifyCashLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyCashLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyCashLabelMousePressed(evt);
            }
        });

        administratorMenuLabel.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        administratorMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        administratorMenuLabel.setText("Administrator Menu");

        eliminateCashLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        eliminateCashLabel.setForeground(new java.awt.Color(0, 0, 255));
        eliminateCashLabel.setText("»Eliminate");
        eliminateCashLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminateCashLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminateCashLabelMousePressed(evt);
            }
        });

        departmentLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        departmentLabel.setText("Department");

        createClieLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        createClieLabel.setForeground(new java.awt.Color(0, 0, 255));
        createClieLabel.setText("»Create");
        createClieLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createClieLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createClieLabelMousePressed(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        categoryLabel.setText("Category");

        modifyClieLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        modifyClieLabel.setForeground(new java.awt.Color(0, 0, 255));
        modifyClieLabel.setText("»Modify");
        modifyClieLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyClieLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyClieLabelMousePressed(evt);
            }
        });

        productLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        productLabel.setText("Product");

        billLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        billLabel.setText("Bill");

        createDepartLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        createDepartLabel.setForeground(new java.awt.Color(0, 0, 255));
        createDepartLabel.setText("»Create");
        createDepartLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createDepartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createDepartLabelMousePressed(evt);
            }
        });

        modifyDepartLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        modifyDepartLabel.setForeground(new java.awt.Color(0, 0, 255));
        modifyDepartLabel.setText("»Modify");
        modifyDepartLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyDepartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyDepartLabelMousePressed(evt);
            }
        });

        eliminateDepartLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        eliminateDepartLabel.setForeground(new java.awt.Color(0, 0, 255));
        eliminateDepartLabel.setText("»Eliminate");
        eliminateDepartLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminateDepartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminateDepartLabelMousePressed(evt);
            }
        });

        createCatgLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        createCatgLabel.setForeground(new java.awt.Color(0, 0, 255));
        createCatgLabel.setText("»Create");
        createCatgLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createCatgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createCatgLabelMousePressed(evt);
            }
        });

        modifyCatgLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        modifyCatgLabel.setForeground(new java.awt.Color(0, 0, 255));
        modifyCatgLabel.setText("»Modify");
        modifyCatgLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyCatgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyCatgLabelMousePressed(evt);
            }
        });

        EliminateProdLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        EliminateProdLabel.setForeground(new java.awt.Color(0, 0, 255));
        EliminateProdLabel.setText("»Eliminate");
        EliminateProdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminateProdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminateProdLabelMousePressed(evt);
            }
        });

        eliminateCatgLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        eliminateCatgLabel.setForeground(new java.awt.Color(0, 0, 255));
        eliminateCatgLabel.setText("»Eliminate");
        eliminateCatgLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminateCatgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminateCatgLabelMousePressed(evt);
            }
        });

        createProdLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        createProdLabel.setForeground(new java.awt.Color(0, 0, 255));
        createProdLabel.setText("»Create");
        createProdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createProdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createProdLabelMousePressed(evt);
            }
        });

        modifyProdLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        modifyProdLabel.setForeground(new java.awt.Color(0, 0, 255));
        modifyProdLabel.setText("»Modify");
        modifyProdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyProdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyProdLabelMousePressed(evt);
            }
        });

        invalidateBillLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        invalidateBillLabel.setForeground(new java.awt.Color(0, 0, 255));
        invalidateBillLabel.setText("»Invalidate");
        invalidateBillLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invalidateBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                invalidateBillLabelMousePressed(evt);
            }
        });

        createBillLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        createBillLabel.setForeground(new java.awt.Color(0, 0, 255));
        createBillLabel.setText("»Create");
        createBillLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createBillLabelMousePressed(evt);
            }
        });

        goBackButton.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        goBackButton.setText("Go Back");
        goBackButton.setBorder(null);
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cashierLabel)
                            .addComponent(createCashLabel)
                            .addComponent(modifyCashLabel)
                            .addComponent(eliminateCashLabel)
                            .addComponent(departmentLabel)
                            .addComponent(createDepartLabel)
                            .addComponent(modifyDepartLabel)
                            .addComponent(eliminateDepartLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(modifyBillLabel)
                            .addComponent(categoryLabel)
                            .addComponent(billLabel)
                            .addComponent(createCatgLabel)
                            .addComponent(modifyCatgLabel)
                            .addComponent(eliminateCatgLabel)
                            .addComponent(invalidateBillLabel)
                            .addComponent(createBillLabel)
                            .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(eliminateClieLabel)
                            .addComponent(clientLabel)
                            .addComponent(createClieLabel)
                            .addComponent(modifyClieLabel)
                            .addComponent(productLabel)
                            .addComponent(EliminateProdLabel)
                            .addComponent(createProdLabel)
                            .addComponent(modifyProdLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(administratorMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(administratorMenuLabel)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departmentLabel)
                    .addComponent(categoryLabel)
                    .addComponent(productLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createDepartLabel)
                    .addComponent(createCatgLabel)
                    .addComponent(createProdLabel))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyDepartLabel)
                    .addComponent(modifyCatgLabel)
                    .addComponent(modifyProdLabel))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminateDepartLabel)
                    .addComponent(eliminateCatgLabel)
                    .addComponent(EliminateProdLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashierLabel)
                    .addComponent(billLabel)
                    .addComponent(clientLabel))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createCashLabel)
                    .addComponent(createBillLabel)
                    .addComponent(createClieLabel))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyCashLabel)
                    .addComponent(modifyBillLabel)
                    .addComponent(modifyClieLabel))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminateCashLabel)
                    .addComponent(invalidateBillLabel)
                    .addComponent(eliminateClieLabel))
                .addGap(18, 18, 18)
                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        queriesMenu.setText("Queries");
        jMenuBar2.add(queriesMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDepartLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createDepartLabelMousePressed
        new AddNewDepartment().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createDepartLabelMousePressed

    private void modifyDepartLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyDepartLabelMousePressed
        new ModifyDepartment().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyDepartLabelMousePressed

    private void eliminateDepartLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminateDepartLabelMousePressed
        new EliminateDepartment().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminateDepartLabelMousePressed

    private void createCatgLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCatgLabelMousePressed
        new AddNewCategory().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createCatgLabelMousePressed

    private void modifyCatgLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyCatgLabelMousePressed
        new ModifyCategory().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyCatgLabelMousePressed

    private void eliminateCatgLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminateCatgLabelMousePressed
        new EliminateCategory().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminateCatgLabelMousePressed

    private void createProdLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createProdLabelMousePressed
        new AddNewProduct().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createProdLabelMousePressed

    private void modifyProdLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyProdLabelMousePressed
        new ModifyProduct().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyProdLabelMousePressed

    private void EliminateProdLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminateProdLabelMousePressed
        new EliminateProduct().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminateProdLabelMousePressed

    private void createCashLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCashLabelMousePressed
        new AddNewCashier().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createCashLabelMousePressed

    private void modifyCashLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyCashLabelMousePressed
        new ModifyCashier().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyCashLabelMousePressed

    private void eliminateCashLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminateCashLabelMousePressed
        new EliminateCashier().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminateCashLabelMousePressed

    private void createBillLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBillLabelMousePressed
        new AddNewBill().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createBillLabelMousePressed

    private void modifyBillLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBillLabelMousePressed
        new ModifyBill().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyBillLabelMousePressed

    private void invalidateBillLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invalidateBillLabelMousePressed
        new InvalidateBill().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_invalidateBillLabelMousePressed

    private void createClieLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createClieLabelMousePressed
        new AddNewClient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createClieLabelMousePressed

    private void modifyClieLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyClieLabelMousePressed
        new ModifyClient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyClieLabelMousePressed

    private void eliminateClieLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminateClieLabelMousePressed
        new EliminateClient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminateClieLabelMousePressed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        Main.administratorConnected = null;
        Main.login.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EliminateProdLabel;
    private javax.swing.JLabel administratorMenuLabel;
    private javax.swing.JLabel billLabel;
    private javax.swing.JLabel cashierLabel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel clientLabel;
    private javax.swing.JLabel createBillLabel;
    private javax.swing.JLabel createCashLabel;
    private javax.swing.JLabel createCatgLabel;
    private javax.swing.JLabel createClieLabel;
    private javax.swing.JLabel createDepartLabel;
    private javax.swing.JLabel createProdLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel eliminateCashLabel;
    private javax.swing.JLabel eliminateCatgLabel;
    private javax.swing.JLabel eliminateClieLabel;
    private javax.swing.JLabel eliminateDepartLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel invalidateBillLabel;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modifyBillLabel;
    private javax.swing.JLabel modifyCashLabel;
    private javax.swing.JLabel modifyCatgLabel;
    private javax.swing.JLabel modifyClieLabel;
    private javax.swing.JLabel modifyDepartLabel;
    private javax.swing.JLabel modifyProdLabel;
    private javax.swing.JLabel productLabel;
    private javax.swing.JMenu queriesMenu;
    // End of variables declaration//GEN-END:variables
}
